### ISSUE TITLE
Document that the provided path should be absolute?

### ISSUE THREAD

**Issue by cjerdonek** [andreyvit/find-fsevents-bugs#1]
Hi, thanks for this helpful program.  One thing that was confusing to me when first using it is that it seems to require the given path to be absolute:

```
$ find-fsevents-bugs PATH
```

For example, if PATH is "." or a relative path to a directory, then it shows all subdirectories as "Found."

Related to this, if you include a trailing slash in the provided directory (which is what tab completion does automatically for me), then it always seems to display that directory as "Found."  This can be misleading, because someone might think this means the directory has the bug when it doesn't.  Rather, it just means that the user passed the directory name in a non-normalized form.

You might want to include these clarifications in the README: (1) that the path should be absolute, and (2) that the "canonical" form of the path should be provided (whatever "canonical" means).

**Comment by andreyvit** [comment]
Hey, and thanks for the nice ideas.

Unfortunately, I'm unlikely to spend more time on this issue; I've already spent more than enough, and it is hopefully fixed in El Capitan.

Pull requests are welcome, though. :-)

**Comment by cjerdonek** [comment]
Cool, that's okay!  Btw, it's possible these issues are addressed after the changes you made a few weeks ago.  I was still using the older version when I filed them.  I also hopefully won't have to be using this utility any longer since I've fixed all the broken folders on my machine. :)

**Comment by cjerdonek** [comment]
> and it is hopefully fixed in El Capitan.

FYI, when I ran this utility after upgrading to El Capitan, I got the following:

```
$ ./find-fsevents-bugs /
Result 1:                                                                      
  readdir:         /dev
  realpath:        /dev
 !FSCopyAliasInfo: /cores
Done, 1 result(s).
```

Do you think this means the problem still exists in some form?

**Comment by andreyvit** [comment]
@cjerdonek Nope, `/dev` always gives a strange result for some reason. It's not an indication of FS failure.
